repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v2.3.0
    hooks:
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: check-xml
    -   id: no-commit-to-branch
        args: [--branch, 12.0-dev]
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: fix-encoding-pragma
        args: ["--remove"]
    -   id: flake8
        name: flake8 except __init__.py
        exclude: /__init__\.py$
        args: [--max-line-length=88]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.3.5
    hooks:
    -   id: reorder-python-imports
        language_version: python3
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v6.5.1
    hooks:
    - id: eslint
      args: ["--resolve-plugins-relative-to=$(npm root -g)"]
      verbose: true
